# ============================================
# ZSH Configuration (Windows Terminal + Starship)
# ============================================
# Warp에서 Windows Terminal로 전환
# Starship 프롬프트 + fzf + zoxide

# ============================================
# PATH
# ============================================
export PATH="$HOME/bin:$HOME/.local/bin:/usr/local/bin:$PATH"

# ============================================
# SSH Agent (keychain)
# ============================================
if command -v keychain &> /dev/null; then
    eval $(keychain --eval --quiet id_ed25519 2>/dev/null)
fi

# ============================================
# GPG (for pass/password-store)
# ============================================
export GPG_TTY=$(tty)

# ============================================
# fnm (Fast Node Manager)
# ============================================
export FNM_DIR="$HOME/.local/share/fnm"
if [ -f "$FNM_DIR/fnm" ]; then
    export PATH="$FNM_DIR:$PATH"
    eval "$(fnm env --use-on-cd --shell zsh)"
fi

# ============================================
# uv (Python package manager)
# ============================================
[ -f "$HOME/.local/bin/env" ] && . "$HOME/.local/bin/env"

# ============================================
# zoxide (smart cd) - 필수!
# ============================================
if command -v zoxide &> /dev/null; then
    eval "$(zoxide init zsh)"
fi

# ============================================
# History 설정
# ============================================
HISTFILE=~/.zsh_history
HISTSIZE=50000
SAVEHIST=50000
setopt HIST_IGNORE_ALL_DUPS
setopt HIST_FIND_NO_DUPS
setopt SHARE_HISTORY

# ============================================
# Modern CLI Aliases (실용적인 것만)
# ============================================

# ls 대체 (eza)
if command -v eza &> /dev/null; then
    alias ls='eza --icons --group-directories-first'
    alias ll='eza -la --icons --group-directories-first --git'
    alias la='eza -a --icons --group-directories-first'
    alias lt='eza --tree --level=2 --icons'
    alias tree='eza --tree --icons --group-directories-first'
fi

# cat 대체 (batcat)
if command -v batcat &> /dev/null; then
    alias cat='batcat --paging=never'
    alias catn='batcat'
fi

# fd 대체
command -v fdfind &> /dev/null && alias fd='fdfind'

# lazygit
command -v lazygit &> /dev/null && alias lg='lazygit'

# ============================================
# Git Aliases
# ============================================
alias gst='git status'
alias gco='git checkout'
alias gcm='git commit -m'
alias gp='git push'
alias gl='git pull'
alias gd='git diff'
alias glog='git log --oneline --graph --decorate'

# ============================================
# Docker Aliases
# ============================================
alias dps='docker ps'
alias dpa='docker ps -a'
alias di='docker images'
alias dcu='docker compose up -d'
alias dcd='docker compose down'
alias dcl='docker compose logs -f'

# ============================================
# Navigation
# ============================================
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias cls='clear'

# ============================================
# Dotfiles Management (bare git repo)
# ============================================
alias config='/usr/bin/git --git-dir=$HOME/.cfg/ --work-tree=$HOME'
alias sync='~/.local/bin/dotfiles-sync.sh'  # 설정 파일 동기화

# Secret Management (pass) - 개별 키 구조
secrets() {
    local cmd="${1:-}"
    local key="${2:-}"
    local STORE_DIR="$HOME/.password-store"

    # .env.local 재생성 함수
    _regenerate_env() {
        mkdir -p "$HOME/.claude"
        cat > "$HOME/.claude/.env.local" << 'HEADER'
# Claude Code MCP 환경변수
# Auto-generated by secrets function
HEADER
        for gpg_file in "$STORE_DIR/claude/"*.gpg; do
            [ -f "$gpg_file" ] || continue
            local k=$(basename "$gpg_file" .gpg)
            local v=$(pass show "claude/$k" 2>/dev/null || echo "")
            [ -n "$v" ] && echo "export $k='$v'" >> "$HOME/.claude/.env.local"
        done
        echo "✓ ~/.claude/.env.local regenerated"
    }

    # push 함수
    _push_store() {
        cd "$STORE_DIR"
        git add -A
        git commit -m "Update secrets from $(hostname)" 2>/dev/null || true
        git push origin main 2>/dev/null || echo "  (push failed)"
        cd - > /dev/null
    }

    case "$cmd" in
        list|ls)
            echo "=== Claude API Keys ==="
            for gpg_file in "$STORE_DIR/claude/"*.gpg; do
                [ -f "$gpg_file" ] || continue
                local k=$(basename "$gpg_file" .gpg)
                echo "  • $k"
            done
            ;;
        edit|e)
            if [ -z "$key" ]; then
                echo "Usage: secrets edit <KEY_NAME>"
                return 1
            fi
            pass edit "claude/$key"
            _push_store
            _regenerate_env
            ;;
        add|a)
            if [ -z "$key" ]; then
                echo "Usage: secrets add <KEY_NAME>"
                echo "Example: secrets add NEW_API_KEY"
                return 1
            fi
            echo -n "Enter value for $key: "
            read -s value
            echo ""
            echo "$value" | pass insert -f "claude/$key"
            _push_store
            _regenerate_env
            ;;
        show|s)
            if [ -z "$key" ]; then
                echo "Usage: secrets show <KEY_NAME>"
                return 1
            fi
            pass show "claude/$key"
            ;;
        regen)
            _regenerate_env
            ;;
        *)
            # 대화형 모드 (기존 setup-secrets.sh 동작)
            if [ -f "$HOME/.local/bin/setup-secrets.sh" ]; then
                bash "$HOME/.local/bin/setup-secrets.sh"
                _regenerate_env
            else
                echo "Usage: secrets <command> [key]"
                echo ""
                echo "Commands:"
                echo "  list          - List all API keys"
                echo "  edit <key>    - Edit specific key"
                echo "  add <key>     - Add new key"
                echo "  show <key>    - Show key value"
                echo "  regen         - Regenerate .env.local"
                echo "  (no args)     - Interactive setup"
            fi
            ;;
    esac
}

# ============================================
# Claude Code
# ============================================
alias cc='claude --dangerously-skip-permissions'

# Claude Code MCP 환경변수
if [ -f ~/.claude/.env.local ]; then
    set -a
    source ~/.claude/.env.local
    set +a
fi

# ============================================
# Windows Chrome (for MCP DevTools)
# ============================================
# Start Windows Chrome with remote debugging enabled
chrome-debug() {
    local CHROME_PATH="/mnt/c/Program Files/Google/Chrome/Application/chrome.exe"
    local USER_DATA_DIR="C:\\temp\\chrome-debug"
    if [ -f "$CHROME_PATH" ]; then
        # Kill existing Chrome to avoid port conflict
        powershell.exe -Command "Stop-Process -Name chrome -Force -ErrorAction SilentlyContinue" 2>/dev/null
        sleep 1
        # mirrored 모드에서는 localhost가 공유되므로 기본 설정으로 충분
        "$CHROME_PATH" --remote-debugging-port=9222 --user-data-dir="$USER_DATA_DIR" &>/dev/null &
        disown
        echo "Chrome started with remote debugging on port 9222"
        echo "User data dir: $USER_DATA_DIR"
    else
        echo "Chrome not found at: $CHROME_PATH"
    fi
}

# ============================================
# VS Code PATH (WSL)
# ============================================
export PATH="$PATH:/mnt/c/Users/kangm/AppData/Local/Programs/Microsoft VS Code/bin"

# ============================================
# Starship Prompt
# ============================================
if command -v starship &> /dev/null; then
    eval "$(starship init zsh)"
fi

# ============================================
# fzf (Fuzzy Finder)
# ============================================
if command -v fzf &> /dev/null; then
    # fzf 키바인딩: Ctrl+R (히스토리), Ctrl+T (파일), Alt+C (디렉토리)
    source /usr/share/doc/fzf/examples/key-bindings.zsh 2>/dev/null || true
    source /usr/share/doc/fzf/examples/completion.zsh 2>/dev/null || true
fi

# ============================================
# Windows Terminal Integration (탭 제목 자동 변경)
# ============================================
# 현재 디렉토리와 명령어를 탭 제목에 표시
function set_win_title() {
    echo -ne "\033]0;${PWD/#$HOME/~}\007"
}
precmd_functions+=(set_win_title)

# ============================================
# Dotfiles 자동 동기화 (터미널 시작 시)
# ============================================
[ -f ~/.local/bin/dotfiles-sync.sh ] && ~/.local/bin/dotfiles-sync.sh

# ============================================
# Chrome Debug 자동 시작 (Claude Code MCP용)
# ============================================
# 9222 포트가 열려있지 않으면 Chrome 디버그 모드 시작
if ! curl -s --connect-timeout 1 http://127.0.0.1:9222/json/version &>/dev/null; then
    chrome-debug &>/dev/null
fi

